### ISSUE TITLE
Error occured while launching the server

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/RedstoneArmory#12]
Using RedstoneArmory-1.7.10-1.1-19-universal.jar
and ttCore-MC1.7.10-0.1.0-56.jar

[21:59:52] [Server thread/ERROR]: [Handlers] main.redstonearmory.gui.ConfigGui threw an error on load, skipping...
[21:59:52] [Server thread/WARN]: java.lang.IllegalStateException: java.lang.ClassNotFoundException: main.redstonearmory.gui.ConfigGui
[21:59:52] [Server thread/WARN]:    at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:269)
[21:59:52] [Server thread/WARN]:    at tterrag.core.common.Handlers.register(Handlers.java:170)
[21:59:52] [Server thread/WARN]:    at tterrag.core.TTCore.init(TTCore.java:74)
[21:59:52] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:59:52] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[21:59:52] [Server thread/WARN]:    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[21:59:52] [Server thread/WARN]:    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[21:59:52] [Server thread/WARN]:    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[21:59:52] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:59:52] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[21:59:52] [Server thread/WARN]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[21:59:52] [Server thread/WARN]:    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[21:59:52] [Server thread/WARN]:    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
[21:59:52] [Server thread/WARN]:    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[21:59:52] [Server thread/WARN]:    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
[21:59:52] [Server thread/WARN]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:280)
[21:59:52] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[21:59:52] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
[21:59:52] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: main.redstonearmory.gui.ConfigGui
[21:59:52] [Server thread/WARN]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:59:52] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[21:59:52] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[21:59:52] [Server thread/WARN]:    at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:266)
[21:59:52] [Server thread/WARN]:    ... 33 more
[21:59:52] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: tterrag/core/client/config/BaseConfigGui
[21:59:52] [Server thread/WARN]:    at java.lang.ClassLoader.defineClass1(Native Method)
[21:59:52] [Server thread/WARN]:    at java.lang.ClassLoader.defineClass(Unknown Source)
[21:59:52] [Server thread/WARN]:    at java.security.SecureClassLoader.defineClass(Unknown Source)
[21:59:52] [Server thread/WARN]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[21:59:52] [Server thread/WARN]:    ... 36 more
[21:59:52] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: tterrag.core.client.config.BaseConfigGui
[21:59:52] [Server thread/WARN]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[21:59:52] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[21:59:52] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[21:59:52] [Server thread/WARN]:    ... 40 more

**Comment by TehNut** [comment]
I cannot reproduce this.

**Comment by TehNut** [comment]
No response in almost 2 weeks. Closing.

**Comment by bochen415** [comment]
Similar error while loading dedicated server:
FML log:
http://paste.ubuntu.com/10360923/
line 12292+

Modlist:
http://paste.ubuntu.com/10360934/

I'll try to minimize the modlist

**Comment by TehNut** [comment]
Can you reproduce with just required mods?

**Comment by bochen415** [comment]
Not crashing.
Log spam only.

FML log:
http://paste.ubuntu.com/10361461/
line 3552+

Modlist:
http://paste.ubuntu.com/10361478/

**Comment by Cronosus** [comment]
same on my cauldron server

**Comment by TehNut** [comment]
It's not an actual crash, so this is very low on my to-do list.

**Comment by TehNut** [comment]
Is this still produce-able?

**Comment by bochen415** [comment]
Happens every time on server start.
http://paste.ubuntu.com/11323965/
Line 14616+

ttCore-MC1.7.10-0.1.1-76.jar
RedstoneArmory-1.7.10-1.2.0-34.jar

**Comment by TehNut** [comment]
I have literally never seen this on my server...

**Comment by bochen415** [comment]
I've deleted the config files to recreate default values in them for RArm an ttcore.
Same thing.

**Comment by bochen415** [comment]
Minimal modlist to recreate:
http://paste.ubuntu.com/11324883/

**Comment by bochen415** [comment]
https://github.com/tterrag1098/WAILAPlugins/issues/33

**Comment by rdelro** [comment]
I only had an issue with server crashes by the gelid blocks being placed in the world. After removing a mod, everything was fine. It may be a conflict with another mod?

**Comment by tterrag1098** [comment]
@TehNut Place your clientside handlers inside a **/client/* package, this will prevent them from being loaded serverside. Yes this armor is harmless but it is a bit spammy.

**Comment by TehNut** [comment]
Will do. Didn't know about that bit.

**Comment by TehNut** [comment]
73131568302e7c4ba30314b32615338dbde2ac2f
